import { HardHat, Hotel, Scale, Sun, UtensilsCrossed } from 'lucide-react';

export const businessSectors = [
  {
    slug: 'ristorazione',
    label: 'Ristorazione',
    icon: UtensilsCrossed,
    eyebrow: 'Ristoranti, pizzerie, bar e locali',
    cardText: 'Strategie locali per far conoscere il tuo locale, generare prenotazioni e far tornare i clienti.',
    tags: ['Ristoranti', 'Pizzerie', 'Bar e locali'],
    metaTitle: 'Marketing per ristoranti, pizzerie e bar | Mago System',
    metaDescription: 'Marketing per la ristorazione: visibilità locale, campagne per prenotazioni, eventi e ritorno dei clienti. Scopri il metodo Mago System.',
    headline: 'Il tuo locale, nella scelta di chi cerca dove andare.',
    subhead: 'Aiutiamo ristoranti, pizzerie, bar e locali a raccontare la propria identità e trasformare la domanda della zona in prenotazioni. Partiamo da cucina, pubblico e giorni su cui vuoi lavorare.',
    outcome: 'Dalla ricerca al tavolo',
    journey: [
      ['Fatti trovare in zona', 'Ricerche locali e occasioni di consumo'],
      ['Dai un motivo per sceglierti', 'Menù, atmosfera e informazioni chiare'],
      ['Semplifica la prenotazione', 'Un percorso diretto verso il tuo locale'],
    ],
    valueTitle: 'Un motivo per venire. Un motivo per tornare.',
    valueText: 'Un pranzo di lavoro, una cena in coppia e una festa hanno esigenze diverse. Costruiamo messaggi e percorsi attorno alle occasioni che contano per il tuo locale.',
    valueCards: [
      { title: 'Identità riconoscibile', text: 'Valorizziamo cucina, ambiente e proposta con contenuti che aiutano a capire quale esperienza aspettarsi.' },
      { title: 'Visibilità nella zona', text: 'Colleghiamo ricerca locale, sito e campagne per raggiungere chi può davvero scegliere il tuo locale.' },
      { title: 'Prenotazioni semplici', text: 'Mettiamo in evidenza menù, orari, posizione e modalità di prenotazione, riducendo i passaggi necessari.' },
      { title: 'Clienti che ritornano', text: 'Progettiamo comunicazioni per novità, serate ed eventi rivolte ai clienti che scelgono di restare in contatto.' },
    ],
    servicesTitle: 'Le occasioni giuste per riempire la tua agenda.',
    services: ['Prenotazioni al tavolo', 'Pranzi di lavoro', 'Serate ed eventi', 'Feste e gruppi', 'Asporto e delivery', 'Ritorno dei clienti'],
    workflowTitle: 'Dal primo interesse alla prossima visita.',
    steps: [
      { title: 'Scegliamo le priorità', text: 'Analizziamo zona, pubblico, scontrino medio e disponibilità per individuare giorni e servizi da promuovere.' },
      { title: 'Colleghiamo i canali', text: 'Sito, contenuti e campagne portano verso una prenotazione, una chiamata o un ordine, secondo il tuo modello di servizio.' },
      { title: 'Leggiamo i risultati', text: 'Confrontiamo le richieste con prenotazioni e presenze effettive per capire quali iniziative meritano continuità.' },
    ],
    metrics: [
      ['Prenotazioni', 'Quante richieste diventano tavoli confermati.'],
      ['Costo per prenotazione', 'Quanto investimento serve per una conferma.'],
      ['Ritorno dei clienti', 'Quante persone scelgono di tornare nel tempo.'],
    ],
    ctaTitle: 'Facciamo spazio al tuo locale nelle scelte della zona.',
    ctaDescription: 'Raccontaci dove lavori, la tua proposta e i momenti della settimana da valorizzare. Costruiamo una prima lettura delle opportunità per la tua attività.',
  },
  {
    slug: 'turismo-ospitalita',
    label: 'Turismo e ospitalità',
    icon: Hotel,
    eyebrow: 'Hotel, B&B e case vacanza',
    cardText: 'Percorsi per valorizzare la tua struttura, aumentare le richieste dirette e lavorare sulla stagionalità.',
    tags: ['Hotel e alberghi', 'B&B', 'Case vacanza e Airbnb'],
    metaTitle: 'Marketing per hotel, B&B e case vacanza | Mago System',
    metaDescription: 'Strategie digitali per hotel, alberghi, B&B e alloggi su Airbnb: prenotazioni dirette, stagionalità e valorizzazione della struttura con Mago System.',
    headline: 'Il prossimo soggiorno comincia da come ti presenti.',
    subhead: 'Costruiamo percorsi digitali per hotel, alberghi, B&B e case vacanza, compresi gli alloggi promossi su Airbnb. Valorizziamo struttura e destinazione per accompagnare l’ospite verso una richiesta o una prenotazione diretta.',
    outcome: 'Dall’ispirazione al soggiorno',
    journey: [
      ['Intercetta il viaggio', 'Destinazione, periodo e motivo del soggiorno'],
      ['Racconta l’esperienza', 'Camere, servizi e territorio'],
      ['Facilita la scelta', 'Disponibilità e prenotazione diretta'],
    ],
    valueTitle: 'La struttura giusta per il viaggio giusto.',
    valueText: 'Chi viaggia per lavoro cerca cose diverse da una famiglia in vacanza. Mettiamo in relazione i tuoi punti di forza con il pubblico e i periodi su cui vuoi crescere.',
    valueCards: [
      { title: 'Ospiti in linea', text: 'Definiamo i segmenti più coerenti con posizione, servizi, fascia di prezzo e tipologia della struttura.' },
      { title: 'Esperienza visibile', text: 'Organizziamo camere, dotazioni, foto e informazioni pratiche in un racconto che rende più facile scegliere.' },
      { title: 'Contatto diretto', text: 'Rendiamo accessibili disponibilità, richieste di preventivo e booking engine, quando presente.' },
      { title: 'Stagionalità gestita', text: 'Pianifichiamo le attività sui periodi di prenotazione, sugli eventi locali e sulle date con disponibilità.' },
    ],
    servicesTitle: 'Ospitalità diversa, percorsi dedicati.',
    services: ['Hotel e alberghi', 'B&B e affittacamere', 'Case vacanza e alloggi Airbnb', 'Soggiorni business', 'Pacchetti ed esperienze', 'Bassa stagione'],
    workflowTitle: 'Dalla destinazione alla conferma della camera.',
    steps: [
      { title: 'Studiamo il soggiorno', text: 'Partiamo da mercati di provenienza, durata media, stagionalità e punti di forza della struttura.' },
      { title: 'Prepariamo il percorso', text: 'Campagne e pagine dedicate mettono in evidenza servizi, condizioni e prossimi passi per chiedere disponibilità.' },
      { title: 'Misuriamo le conferme', text: 'Colleghiamo, dove i sistemi lo consentono, richieste, prenotazioni e ricavi per valutare il contributo dei canali.' },
    ],
    metrics: [
      ['Prenotazioni dirette', 'Le conferme che arrivano dai tuoi canali.'],
      ['Costo di acquisizione', 'L’investimento per ottenere una prenotazione.'],
      ['Valore del soggiorno', 'Il ricavo delle prenotazioni attribuibili alle attività.'],
    ],
    ctaTitle: 'Diamo più visibilità all’esperienza che offri.',
    ctaDescription: 'Analizziamo struttura, destinazione, canali attivi e periodi prioritari per individuare come sostenere le richieste e le prenotazioni dirette.',
  },
  {
    slug: 'edilizia-ristrutturazioni',
    label: 'Edilizia e ristrutturazioni',
    icon: HardHat,
    eyebrow: 'Ristrutturazioni chiavi in mano',
    cardText: 'Acquisizione di richieste per ristrutturazioni chiavi in mano, con attenzione a zona, intervento e budget.',
    tags: ['Chiavi in mano', 'Ristrutturazioni complete', 'Sopralluoghi'],
    metaTitle: 'Marketing per edilizia e ristrutturazioni chiavi in mano | Mago System',
    metaDescription: 'Campagne e pagine per imprese edili e ristrutturazioni chiavi in mano. Qualifica le richieste per zona, progetto e budget con Mago System.',
    headline: 'Progetti più in linea con la tua impresa, dal primo contatto.',
    subhead: 'Aiutiamo imprese edili e aziende di ristrutturazione chiavi in mano a presentare il proprio metodo e ricevere richieste più complete. Zona, tipo di immobile, tempi e budget diventano parte del percorso prima del sopralluogo.',
    outcome: 'Dall’idea al sopralluogo',
    journey: [
      ['Intercetta il progetto', 'Immobile, zona e intervento desiderato'],
      ['Mostra come lavori', 'Cantieri, competenze e gestione del progetto'],
      ['Prepara il sopralluogo', 'Informazioni utili prima dell’appuntamento'],
    ],
    valueTitle: 'La fiducia si costruisce prima di entrare in cantiere.',
    valueText: 'Una ristrutturazione completa richiede una scelta ponderata. Spieghiamo cosa comprende il servizio chiavi in mano e rendiamo leggibile il percorso dal progetto alla consegna.',
    valueCards: [
      { title: 'Progetti compatibili', text: 'Orientiamo le campagne verso aree servite, tipologie di immobili e dimensioni di intervento adatte alla tua impresa.' },
      { title: 'Lavori che raccontano', text: 'Valorizziamo cantieri documentati e realizzazioni per mostrare qualità, organizzazione e competenze del team.' },
      { title: 'Richieste complete', text: 'Raccogliamo tipo di lavoro, metratura indicativa, tempi e budget per preparare un primo confronto utile.' },
      { title: 'Continuità commerciale', text: 'Organizziamo il seguito di richieste, sopralluoghi e preventivi per dare a ogni progetto un passo successivo.' },
    ],
    servicesTitle: 'Il chiavi in mano, spiegato in ogni passaggio.',
    services: ['Ristrutturazioni chiavi in mano', 'Appartamenti e case', 'Ville e immobili indipendenti', 'Bagni e cucine', 'Locali commerciali', 'Progettazione e coordinamento lavori'],
    workflowTitle: 'Dalla richiesta generica al progetto da valutare.',
    steps: [
      { title: 'Definiamo il cantiere ideale', text: 'Mettiamo a fuoco area operativa, capacità dell’impresa, lavori prioritari e soglia di investimento del progetto.' },
      { title: 'Spieghiamo e qualifichiamo', text: 'Campagne e pagine mostrano metodo e realizzazioni, con domande mirate a capire l’intervento richiesto.' },
      { title: 'Seguiamo le opportunità', text: 'Leggiamo il passaggio da contatto a sopralluogo, preventivo e lavoro acquisito insieme al tuo team commerciale.' },
    ],
    metrics: [
      ['Richieste in target', 'Contatti coerenti con zona e tipologia di intervento.'],
      ['Sopralluoghi fissati', 'Le richieste che diventano un incontro sul posto.'],
      ['Preventivi accettati', 'Le opportunità che si trasformano in lavori acquisiti.'],
    ],
    ctaTitle: 'Partiamo dai cantieri su cui vuoi far crescere l’impresa.',
    ctaDescription: 'Raccontaci area operativa, tipologie di ristrutturazione e capacità del team. Individuiamo come attirare e gestire richieste più coerenti con il tuo lavoro.',
  },
  {
    slug: 'efficientamento-energetico',
    label: 'Efficientamento energetico',
    icon: Sun,
    eyebrow: 'Impianti, infissi e comfort abitativo',
    cardText: 'Campagne dedicate a fotovoltaico, infissi, pompe di calore e climatizzazione, dalla richiesta al sopralluogo.',
    tags: ['Fotovoltaico', 'Infissi', 'Pompe di calore', 'Climatizzazione'],
    metaTitle: 'Marketing per fotovoltaico, infissi e impianti | Mago System',
    metaDescription: 'Lead generation per efficientamento energetico: fotovoltaico, infissi, pompe di calore e climatizzazione. Percorsi dedicati con Mago System.',
    headline: 'Richieste più adatte alle soluzioni che installi.',
    subhead: 'Costruiamo campagne e percorsi di acquisizione per aziende di fotovoltaico, infissi, pompe di calore e climatizzazione. Distinguiamo ogni soluzione per bisogno, caratteristiche dell’immobile e area servita.',
    outcome: 'Dal bisogno alla valutazione',
    journey: [
      ['Distingui la soluzione', 'Fotovoltaico, infissi o climatizzazione'],
      ['Raccogli il contesto', 'Immobile, esigenza e zona di installazione'],
      ['Avvia il confronto tecnico', 'Una richiesta pronta per essere valutata'],
    ],
    valueTitle: 'Ogni intervento parte da un’esigenza diversa.',
    valueText: 'Produrre energia, sostituire gli infissi e migliorare il comfort richiedono percorsi distinti. Comunichiamo i vantaggi della soluzione e lasciamo al confronto tecnico la valutazione del singolo immobile.',
    valueCards: [
      { title: 'Campagne per soluzione', text: 'Separiamo fotovoltaico, infissi, pompe di calore e climatizzazione per allineare ricerche, annunci e pagine.' },
      { title: 'Informazioni utili', text: 'Raccogliamo area, tipologia di immobile, intervento desiderato e tempistiche per agevolare il primo contatto.' },
      { title: 'Valore comprensibile', text: 'Presentiamo prodotti, installazione e assistenza con messaggi chiari, senza ridurre tutto al prezzo iniziale.' },
      { title: 'Percorso commerciale', text: 'Colleghiamo richiesta, richiamata, sopralluogo e preventivo per capire dove si interrompe la conversazione.' },
    ],
    servicesTitle: 'Quattro aree, una strategia per ciascuna.',
    services: ['Fotovoltaico residenziale', 'Fotovoltaico per aziende', 'Sostituzione infissi', 'Pompe di calore', 'Climatizzazione', 'Soluzioni integrate per la casa'],
    workflowTitle: 'Dall’interesse per il prodotto al sopralluogo tecnico.',
    steps: [
      { title: 'Scegliamo prodotto e area', text: 'Definiamo soluzioni prioritarie, copertura territoriale e capacità di installazione prima di attivare le campagne.' },
      { title: 'Costruiamo pagine dedicate', text: 'Ogni percorso spiega il servizio e raccoglie le informazioni iniziali necessarie al tuo team per ricontattare la persona.' },
      { title: 'Valutiamo gli esiti', text: 'Confrontiamo canali e prodotti sulla qualità dei contatti, sui sopralluoghi effettuati e sui preventivi che diventano clienti.' },
    ],
    metrics: [
      ['Contatti pertinenti', 'Richieste in area per i prodotti che installi.'],
      ['Sopralluoghi effettuati', 'Le opportunità arrivate alla valutazione tecnica.'],
      ['Clienti acquisiti', 'I preventivi confermati, distinti per soluzione.'],
    ],
    ctaTitle: 'Diamo a ogni soluzione il suo percorso di acquisizione.',
    ctaDescription: 'Analizziamo prodotti, area servita e gestione commerciale per costruire campagne orientate a richieste che il tuo team possa valutare e seguire.',
  },
  {
    slug: 'studi-legali',
    label: 'Studi legali',
    icon: Scale,
    eyebrow: 'Avvocati e studi professionali',
    cardText: 'Presenza digitale e richieste di contatto coerenti con le aree di attività del tuo studio legale.',
    tags: ['Persone e famiglie', 'Imprese', 'Consulenze'],
    metaTitle: 'Marketing per avvocati e studi legali | Mago System',
    metaDescription: 'Strategia digitale per avvocati e studi legali: posizionamento, contenuti informativi, ricerca locale e richieste di consulenza con Mago System.',
    headline: 'Rendi chiaro a chi puoi essere d’aiuto.',
    subhead: 'Aiutiamo avvocati e studi legali a presentare competenze, aree di attività e modalità di contatto. Costruiamo una presenza digitale sobria, che accompagna persone e imprese verso una prima richiesta di consulenza.',
    outcome: 'Dal bisogno al primo colloquio',
    journey: [
      ['Chiarisci le aree di attività', 'Materie trattate e persone a cui ti rivolgi'],
      ['Presenta lo studio', 'Professionisti, approccio e modalità di lavoro'],
      ['Agevola il contatto', 'Un primo colloquio da concordare'],
    ],
    valueTitle: 'Competenza leggibile, contatto più semplice.',
    valueText: 'Chi cerca uno studio deve capire se tratta il proprio ambito e come avviare un confronto. Organizziamo i contenuti per dare queste risposte con chiarezza e misura.',
    valueCards: [
      { title: 'Aree ben definite', text: 'Costruiamo pagine distinte per le materie effettivamente trattate, con contenuti concordati con i professionisti.' },
      { title: 'Autorevolezza concreta', text: 'Valorizziamo profili, esperienza e metodo di lavoro attraverso una presentazione informativa e verificabile.' },
      { title: 'Primo contatto discreto', text: 'Rendiamo chiare le modalità di appuntamento e limitiamo il modulo iniziale alle informazioni essenziali.' },
      { title: 'Richieste pertinenti', text: 'Organizziamo i contatti per area di interesse e modalità di consulenza, facilitando la valutazione iniziale dello studio.' },
    ],
    servicesTitle: 'Una comunicazione costruita sulle tue aree di attività.',
    services: ['Diritto civile', 'Famiglia e successioni', 'Diritto del lavoro', 'Diritto societario', 'Contrattualistica', 'Recupero crediti'],
    servicesNote: 'Sono esempi di ambiti: il percorso viene costruito esclusivamente sulle materie trattate dal tuo studio.',
    workflowTitle: 'Dalla ricerca online a un confronto con lo studio.',
    steps: [
      { title: 'Definiamo il posizionamento', text: 'Individuiamo aree di attività, pubblico, territorio e modalità di consulenza su cui concentrare la comunicazione.' },
      { title: 'Prepariamo i contenuti', text: 'Sviluppiamo pagine e messaggi informativi da verificare insieme allo studio, con un percorso di contatto essenziale.' },
      { title: 'Valutiamo la pertinenza', text: 'Misuriamo provenienza delle richieste e colloqui fissati per migliorare i canali in base alle esigenze dello studio.' },
    ],
    metrics: [
      ['Richieste pertinenti', 'Contatti relativi alle materie trattate dallo studio.'],
      ['Colloqui fissati', 'Le richieste che portano a un appuntamento.'],
      ['Canali di provenienza', 'Le fonti delle richieste utili allo studio.'],
    ],
    ctaTitle: 'Facciamo capire il valore e le competenze del tuo studio.',
    ctaDescription: 'Partiamo dalle materie trattate, dal pubblico e dalla presenza digitale attuale per individuare un percorso di comunicazione adatto ai tuoi obiettivi.',
  },
];
